# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-25 23:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='last_name',
            new_name='Alias',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='Name',
        ),
    ]
