# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-26 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='authors',
            field=models.ManyToManyField(related_name='favourites', to='quotes.User'),
        ),
    ]
